webBaseUrl=https://adobe-eyeplus.newstore.co.in/
demourl=https://mcstaging.titaneyeplus.com/rest/
liveurl=https://api.eyeplus.newstore.co.in/rest/
mobileBaseUrl=https://mcstaging.titaneyeplus.com/rest/
backendBaseUrl=https://mcstaging.titaneyeplus.com/rest/default/V1
verifyOtpEndpoint=/api/verify-otp

test.mobile.number=8779906355
test.mobile.otp=654321