webBaseUrl=https://adobe-eyeplus.newstore.co.in/
mobileBaseUrl=https://mcstaging.titaneyeplus.com/rest/V2/titan-mobileapi
backendBaseUrl=https://mcstaging.titaneyeplus.com/rest/default/V1
verifyOtpEndpoint=/api/verify-otp